#!/usr/bin/perl
#

use RPi::PIGPIO;
use RPi::PIGPIO::Device::DHT22;

my $pi = RPi::PIGPIO->connect('127.0.0.1');

my $dht22 = RPi::PIGPIO::Device::DHT22->new($pi,4);

sleep(2);

print "Initiated. Triggering...\n"; 
$dht22->trigger(); #trigger a read

sleep(2);
print "Temperature : ".$dht22->temperature."\n";
print "Humidity : ".$dht22->humidity."\n";

