#!/usr/bin/env python

import sys
import os
import time
import RPi.GPIO as GPIO

sys.stdout.flush()

cnt = 0
avg = 0

# Handle Pulse
def handlePulse (pin):
	global cnt
	cnt += 1

#GPIO.setwarnings(false)

GPIO.setmode(GPIO.BCM)
GPIO.setup(23,GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
GPIO.add_event_detect(23,GPIO.FALLING)
GPIO.add_event_callback(23,handlePulse)

# let a cycle of clicks build up.
time.sleep(60)

while True:
	avg = ((avg * 4) + cnt) / 5
	print "Average = " + str(avg)
	cmd = "rrdtool update /home/pi/furnace/radiation.rrd " + str(int(time.time())) + ":" + str(cnt)
	print cmd
	sys.stdout.flush()
	os.system(cmd)
	#if avg > 30:
		#cmd = "/home/pi/furnace/tweet 'Radiation notice. Time= " + str(int(time.time())) + " 5 Min Avg Count='" + str(avg)
		#os.system(cmd)
	cnt = 0
	time.sleep(60)

GPIO.cleanup()

