#!/usr/bin/perl

use POSIX;

$l_time = time;
($sec,$min,$curr_hour,$mday,$mon,$year,$wday,$yday,$isdst)=localtime($l_time);

if ($ARGV[0] < 0)
  {
    $year+=$ARGV[0];
  }
#my $unixtime = mktime ($sec, $min, $hour, $day, $mon, $year, $wday, $yday);
my $unixtime = mktime (0, 0, 0, $mday, $mon, $year, 0, 0);

print $unixtime;

if ($ARGV[1])
{
 print "\nd:$mday m:$mon y:$year\n";
}
