#!/usr/bin/perl

use POSIX;

$l_time = time;
($sec,$min,$curr_hour,$mday,$mon,$year,$wday,$yday,$isdst)=localtime($l_time);

if ($mon < $ARGV[0]) {$year-=1;}
if ($ARGV[1] > 0)
  {
    $year = $ARGV[1];
    if ($year > 1900)
      {$year-=1900;}
  }
if ($ARGV[1] < 0)
  {
    $year+=$ARGV[1];
  }
#my $unixtime = mktime ($sec, $min, $hour, $day, $mon, $year, $wday, $yday);
my $unixtime = mktime (0, 0, 0, 0, $ARGV[0], $year, 0, 0);

print $unixtime;

