#!/usr/bin/perl
#

# loop forever

if (`ps -e | grep logCOTHAS`) 
{
;
} else {

	# restart process

	my $st = time;
	print "STARTING: $st\n";

	system("mv /home/pi/furnace/logs/COTHAS_err.log /home/pi/furnace/logs/COTHAS_err__$st.log");	
	system("/home/pi/furnace/logCOTHAS >> /home/pi/furnace/logs/COTHAS_err.log 2>&1 &") ;
}
